### ISSUE TITLE
OBSFS access mode ReadOnlyMany not works correctly

### ISSUE THREAD

**Issue by louie007** [huaweicloud/huaweicloud-csi-driver#122]
Using this example template to create PV and PVC
1) examples/obs-csi-plugin/kubernetes/use-existing-bucket/pv.yaml
2) examples/obs-csi-plugin/kubernetes/use-existing-bucket/pvc.yaml

Alter access mode to ReadOnlyMany not works correctly, the bucket is still writable, any idea ?

**Comment by chengxiangdong** [comment]
In Kubernetes, the accessModes field in a PersistentVolumeClaim (PVC) is used to specify the access mode of the claim. `ReadOnlyMany` is one of the access modes, indicating that the PVC can be mounted by multiple Pods in read-only mode.

However, it's important to note that the accessModes field only controls the access mode of the PVC to the underlying persistent storage. It does not restrict write operations on the mounted filesystem within the Pods. Even if the PVC is using the `ReadOnlyMany` access mode, Pods can still perform write operations internally.

In practice, the accessModes field serves as a constraint for the PVC to guide Kubernetes in selecting and allocating appropriate persistent storage based on the access mode. If you want to limit write operations on the mounted filesystem within the Pods, you need to configure it within the Pod's configuration. For example, you can use the readOnly field to set the VolumeMount as read-only mode.

Here's an example Pod configuration that sets the mounted volume as read-only:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-obs
spec:
  containers:
    - image: nginx
      name: nginx-obs
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date -u) >> /mnt/obs/outfile; sleep 5; done"]
      volumeMounts:
        - mountPath: /mnt/obs
          name: obs-data
          readOnly: true
  volumes:
    - name: obs-data
      persistentVolumeClaim:
        claimName: pvc-obs
```

By setting the readOnly field to true, the container inside the Pod can only access the mounted volume in read-only mode. This way, even if the PVC has the ReadOnlyMany access mode, write operations within the Pod will be restricted.
