### ISSUE TITLE
obs csi 不支持OpenEuler系统

### ISSUE THREAD

**Issue by magicJie** [huaweicloud/huaweicloud-csi-driver#126]
![image](https://github.com/huaweicloud/huaweicloud-csi-driver/assets/6937525/baae97ac-3641-45fb-830d-c278586ac060)
![image](https://github.com/huaweicloud/huaweicloud-csi-driver/assets/6937525/1a3ee3a4-d0df-4775-bf0b-9addc3c92942)

这个插件是设计就没考虑OpenEuler系统还是bug，在华为云上基于Rancher自建的k8s想使用obs存储，找了一圈没有解决方案

**Comment by chengxiangdong** [comment]
您好，可以提供一下 csi-obs-controller(容器：obs-csi-plugin) 和 csi-obs-plugin(容器：obs) 的日志吗？

**Comment by magicJie** [comment]
[csi-obs-controller-6ddf4c76c5-jqsgn_obs-csi-plugin.log](https://github.com/huaweicloud/huaweicloud-csi-driver/files/12167215/csi-obs-controller-6ddf4c76c5-jqsgn_obs-csi-plugin.log)
[csi-obs-plugin-8nq64_obs.log](https://github.com/huaweicloud/huaweicloud-csi-driver/files/12167219/csi-obs-plugin-8nq64_obs.log)
![image](https://github.com/huaweicloud/huaweicloud-csi-driver/assets/6937525/336a06c1-e8a8-4d09-b009-6216053b7c09)

**Comment by chengxiangdong** [comment]
`cat /etc/os-release` 获取的是操作系统的版本和信息，我需要插件运行的log，可参考一下命令获取：

获取controller的log：
```
kubectl logs pod/csi-evs-controller-xxxx  evs-csi-provisioner -n kube-system > csi-controller.log

## 请将 csi-evs-controller-xxxx 替换为集群中实际运行的pod名称。
```

获取plugin的log：
```
kubectl logs pod/pod/csi-evs-plugin-764q8  obs-n kube-system > csi-plugin.log

## 请将 csi-evs-controller-xxxx 替换为集群中实际运行的pod名称。
```

**Comment by magicJie** [comment]
![image](https://github.com/huaweicloud/huaweicloud-csi-driver/assets/6937525/9a2877e6-2da3-4c1f-8209-a9a0f5670308)

日志输出很少

**Comment by magicJie** [comment]
看日志提示在启动校验节点就判断不支持了
![image](https://github.com/huaweicloud/huaweicloud-csi-driver/assets/6937525/8e4a3225-d182-44b4-a056-66a0bd62a67c)

**Comment by chengxiangdong** [comment]
看明白了，是在启动时校验出错，这是一个bug。
我们修复一下，预计下周发布一个小版本

**Comment by chengxiangdong** [comment]
发布了一个新版本支持在 OpenEuler 等系统上运行 OBS CSI，请重新安装验证一下，controller 和 node 都有调整需要重新安装，请参考：[OBS文档](https://github.com/huaweicloud/huaweicloud-csi-driver/blob/master/docs/obs/obs.md)。

需要注意，OpenEuler 系统需要编译安装 [obsfs](https://support.huaweicloud.com/fstg-obs/obs_12_0001.html)，请确保在节点上能够成功安装 obsfs 所需要的依赖，目前版本需要如下依赖：

```
yum install -y gcc libstdc++-devel gcc-c++ fuse fuse-devel curl-devel libxml2-devel mailcap git automake make 
yum install -y openssl-devel
```

OBS CSI 启动时自动安装依赖、编译 obsfs 并安装 obsfs，如果手动能够安装依赖，插件也能自动安装。

请先验证一下，有问题可随时沟通。

**Comment by magicJie** [comment]
已经验证完成了，可以通过pod写入文件到并行文件系统。
还有个疑问就是，由于obs限制总的bucket数量为100个，如果pvc比较多还是蛮容易出现配额不足的情况。有办法避免么。

**Comment by chengxiangdong** [comment]
OBS一般是用来存储各类文件，常用于跨应用共享文件，单个桶复用性比较高，一般情况下不容易超过限额。
如果确实需要创建很多，可以采取如下几个方案：

**方案一：** 根据业务特点，选择使用SFS Turbo替代。
**方案二：** 多个项目时，建议使用桶内文件夹管理项目，即多个项目使用同一个并行文件系统，但是每个项目使用不同的文件夹。

部署脚本：
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-a
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-a
  template:
    metadata:
      labels:
        app: project-a
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: obs-data
              mountPath: /app/data/
              subPath: projectA
      volumes:
        - name: obs-data
          persistentVolumeClaim:
            claimName: pvc-obs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-b
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-b
  template:
    metadata:
      labels:
        app: project-b
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: obs-data
              mountPath: /app/data/
              subPath: projectB
      volumes:
        - name: obs-data
          persistentVolumeClaim:
            claimName: pvc-obs
```

通过以上脚本部署两个应用：`project-a` 和 `project-b`，两个应用共用同一个PVC，分别使用桶内的 `projectA` 和 `projectB` 两个文件夹。在应用内部是看不到各自目录之外的内容的。

**方案三：** 提单申请扩大配额，不过OBS本身不支持调整配额，推荐使用按文件夹区分项目。

通过以上几个方案可以避免超过限额产生的问题，您看一下还有其他问题吗？
