### ISSUE TITLE
Add the allow_other parameter for the OBS storage plug

### ISSUE THREAD

**Issue by lsjshilly** [huaweicloud/huaweicloud-csi-driver#139]
`mountFlags := []string{"big_writes", "max_write=131072", "use_ino"}`
------------------------
If the `allow_other` parameter is not modified, other users do not have the permission to access the persistent volume directory.

**Comment by chengxiangdong** [comment]
Hello, 
by default, the `allow_other` attribute is not present. If needed, you can add it in `mountOptions` as follows:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: obs-sc
provisioner: obs.csi.huaweicloud.com
reclaimPolicy: Delete
mountOptions:
  - allow_other
parameters:
  acl: public-read-write
```
