### ISSUE TITLE
external-snapshotter choose which version？

### ISSUE THREAD

**Issue by huntkalio** [huaweicloud/huaweicloud-csi-driver#159]
I wan't to use snaptshot , I found it relay:  [CSI Snapshotter](https://github.com/kubernetes-csi/external-snapshotter),

Which version of external-snapshotter controller and it's crds should I use?

**Comment by chengxiangdong** [comment]
Current versions of CSI Snapshotter are all supported, with newer versions offering more features and functionalities. 
The example we provide has been tested on before version 7.0.

**Comment by huntkalio** [comment]
ok,thanks.

**Comment by huntkalio** [comment]
I test it with external-snapshotter and its crd version 8.1.0.When create snapshot, it failed with 
```
 could not sync content "snapcontent-bee9d218-0f5a-45a3-9068-xxxxx: failed to add VolumeSnapshotBeingCreated annotation on the content snapcontent-bee9d218-0f5a-45a3-9068-xxxxx: "snapshot controller failed to update snapcontent-bee9d218-0f5a-45a3-9068-xxxxxon API server: VolumeSnapshotContent.snapshot.storage.k8s.io \"snapcontent-bee9d218-0f5a-45a3-9068-xxxxx\" is invalid: spec: Invalid value: \"object\": sourceVolumeMode is required once set"
```
sourceVolumeMode

**Comment by chengxiangdong** [comment]
Hi @huntkalio , 
SourceVolumeMode is the mode of the volume whose snapshot is taken.
Can be either `Filesystem` or `Block`, and EVS should use `Block`.

**Comment by huntkalio** [comment]
> Hi @huntkalio , SourceVolumeMode is the mode of the volume whose snapshot is taken. Can be either `Filesystem` or `Block`, and EVS should use `Block`.

this error occur when creat VolumeSnapshot like ‘https://github.com/huaweicloud/huaweicloud-csi-driver/blob/master/examples/evs-csi-plugin/kubernetes/snapshot/snapshot-create.yaml’。

The VolumeSnapshotContent resource is created auto by snap csi  controller? How to set  SourceVolumeMode  in  VolumeSnapshot

**Comment by huntkalio** [comment]
finaly, I solve this by:
1. update https://github.com/huaweicloud/huaweicloud-csi-driver/blob/master/deploy/evs-csi-plugin/kubernetes/csi-evs-controller.yaml  k8s.gcr.io/sig-storage/csi-snapshotter:v4.2.1 to  v8.0.1
2. update https://github.com/huaweicloud/huaweicloud-csi-driver/blob/master/deploy/evs-csi-plugin/kubernetes/rbac-csi-evs-controller.yaml  csi-snapshotter-role like below
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-snapshotter-role
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "watch", "update", "patch", "create"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["get", "list", "watch", "update", "patch", "create"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents/status"]
    verbs: ["update", "patch"]
  - apiGroups: ["groupsnapshot.storage.k8s.io"]
    resources: ["volumegroupsnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["groupsnapshot.storage.k8s.io"]
    resources: ["volumegroupsnapshotcontents"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["groupsnapshot.storage.k8s.io"]
    resources: ["volumegroupsnapshotcontents/status"]
    verbs: ["update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
```
from https://github.com/kubernetes-csi/external-snapshotter/blob/v8.1.0/deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml
