### ISSUE TITLE
StorageClass的参数availabilityZone 无效

### ISSUE THREAD

**Issue by simonwu-os** [huaweicloud/huaweicloud-csi-driver#163]
需要创建华东-上海二的可用区一的云硬盘。
设置如下:
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: evs-ssd
provisioner: evs.csi.huaweicloud.com
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: SSD        # 云硬盘类型（SSD/SAS/GPSSD）
  availabilityZone: cn-east-2a
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode:  WaitForFirstConsumer ##| Immediate

第一次，能够在可用区一创建云硬盘。删除pvc之后，后面多次创建都是华东-上海二的可用区2，不是可用区1.
感觉availabilityZone 参数无效.

**Comment by simonwu-os** [comment]
find the docs.  It uses availability.

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: evs-ssd
provisioner: evs.csi.huaweicloud.com
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: SSD        # 云硬盘类型（SSD/SAS/GPSSD）
  availability: cn-east-2a  # 必须与节点所在AZ一致！
  scsi: "true"
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

It works now.

**Comment by chengxiangdong** [comment]
推荐使用topology特性，参考如下脚本创建SC，当创建PVC的时候会根据容器所在的可用区创建EVS

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: evs-sc
provisioner: evs.csi.huaweicloud.com
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.evs.csi.huaweicloud.com/zone
        values:
          - cn-east-2a
          - cn-east-2b
          - cn-east-2c
parameters:
  type: SSD
```
